name: acha_facil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localization: ^0.3.1
  shared_preferences: ^2.3.5
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
